// Generated by https://quicktype.io

export interface FavoriteWord {
    userId:      string;
    word:        string;
    definition:  string;
    source:      string;
    phonetics:   string;
    context:     string;
    audioSource: string;
    id:          number;
}



