
// Generated by https://quicktype.io

import { FavoriteWord } from "./favorite-words";

export interface UserTable {
    googleId:       string;
    langPreference: string;
    favoriteWords: FavoriteWord [];
}
